--- #YAML:1.0
name:               Test-TempDir
version:            0.05
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::NFSLock:        0
    File::Path:           2.04
    File::Spec:           0
    File::Temp:           0
    Moose:                0.87
    MooseX::Types::Path::Class:  0
    namespace::clean:     0.08
    Path::Class:          0
    Sub::Exporter:        0
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
